before_install:
  - git clone --recursive https://github.com/rust-lang/cargo
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update

install:
  - sudo apt-get install rust-nightly gnuplot
  - cd cargo && make && sudo make install && cd .. && sudo rm -rf cargo

script:
  - make
  - make test

branches:
  only: master
