language: rust

before_install:
  # This PPA has a newer version of gnuplot
  - sudo add-apt-repository ppa:gladky-anton/precise-backports -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gnuplot

script:
  - cargo build --verbose
  - cargo test --verbose
  - ./check-line-length.sh

branches:
  only: master
