environment:
  global:
    TARGET: x86_64-pc-windows-msvc
  matrix:
    - RUST_VERSION: 1.9.0
    - RUST_VERSION: beta
    - RUST_VERSION: nightly

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:RUST_VERSION}-${env:TARGET}.exe"
  - rust-%RUST_VERSION%-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V
  - ps: Start-FileDownload "https://sourceforge.net/projects/gnuplot/files/gnuplot/4.6.7/gp467-win64-setup.exe";
  - gp467-win64-setup.exe /VERYSILENT /NORESTART
  - SET PATH=%PATH%;C:\Program Files\gnuplot\bin

build: false

test_script:
  - cargo build --verbose
  - cargo test
  - cargo doc

branches:
  only:
    - master
